/* Generated by bin2c, do not edit manually */
#ifndef __int16_h_included
#define __int16_h_included

/* Contents of file int16.o */
extern "C" const long int int16_o_size;
extern "C" const unsigned char int16_o[332];

#endif    /* __int16_h_included */
